### ISSUE TITLE
Tax only if Soc Member online

### ISSUE THREAD

**Issue by nopain8269** [LetsTiger/tg_taxsystem#1]
Hi,

its possible to create the tax without having the requirement to have an police member online? because at the moment if no police member is in job we getting following message:
[  script:esx_billing] [ERROR] Player 1 Attempted to Send bill from a society (society_police), but does not have the correct Job - Possibly Cheats

it should be possible to create tax invoices without the requirement to have minimum 1 team member online =)

would be great.

best regards

**Comment by LetsTiger** [comment]
> Hi,
> 
> its possible to create the tax without having the requirement to have an police member online? because at the moment if no police member is in job we getting following message: [ script:esx_billing] [ERROR] Player 1 Attempted to Send bill from a society (society_police), but does not have the correct Job - Possibly Cheats
> 
> it should be possible to create tax invoices without the requirement to have minimum 1 team member online =)
> 
> would be great.
> 
> best regards

Hi @nopain8269 ,

Sorry for the late reply. This is not because no police member is online, but due to an update of the `esx_billing` script. If you're still interested, drop me a DM on Discord (lets_tiger) and I'll help you out. This repository will be updated at a later date.

Best regards

**Comment by LetsTiger** [comment]
This Bug was fixed with a workaround in [v1.3](https://github.com/LetsTiger/tg_taxsystem/releases/tag/v1.3).
